version: "3.0"
services:
  frontend:
    container_name: frontend
    image: node:16.13.2
    working_dir: /app
    volumes:
      - ./:/app
    ports: 
      - 8080:8080
    command: sh -c "npm install && npm start"